apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-deployment
spec:
  selector:
    matchLabels:
      run: backend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        run:  backend-deployment
    spec:
      containers:
      - name:  backend-deployment
        image: backend
        imagePullPolicy: IfNotPresent
