apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-deployment
  ports:
    - protocol: TCP
      port: 15000
      nodePort: 31000
      targetPort: 15000
