apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  frontend-deployment
    spec:
      containers:
      - name:  frontend-deployment
        image: frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 15000
